/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Rosgraph
{
    public class Clock : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "rosgraph_msgs/Clock";

        //  roslib/Clock is used for publishing simulated time in ROS. 
        //  This message simply communicates the current time.
        //  For more information, see http://www.ros.org/wiki/Clock
        public Time clock;

        public Clock()
        {
            this.clock = new Time();
        }

        public Clock(Time clock)
        {
            this.clock = clock;
        }
    }
}
