//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.LivoxRosDriver
{
    [Serializable]
    public class CustomPointMsg : Message
    {
        public const string k_RosMessageName = "livox_ros_driver/CustomPoint";
        public override string RosMessageName => k_RosMessageName;

        //  Livox costom pointcloud format.
        public uint offset_time;
        //  offset time relative to the base time
        public float x;
        //  X axis, unit:m
        public float y;
        //  Y axis, unit:m
        public float z;
        //  Z axis, unit:m
        public byte reflectivity;
        //  reflectivity, 0~255
        public byte tag;
        //  livox tag
        public byte line;
        //  laser number in lidar

        public CustomPointMsg()
        {
            this.offset_time = 0;
            this.x = 0.0f;
            this.y = 0.0f;
            this.z = 0.0f;
            this.reflectivity = 0;
            this.tag = 0;
            this.line = 0;
        }

        public CustomPointMsg(uint offset_time, float x, float y, float z, byte reflectivity, byte tag, byte line)
        {
            this.offset_time = offset_time;
            this.x = x;
            this.y = y;
            this.z = z;
            this.reflectivity = reflectivity;
            this.tag = tag;
            this.line = line;
        }

        public static CustomPointMsg Deserialize(MessageDeserializer deserializer) => new CustomPointMsg(deserializer);

        private CustomPointMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.offset_time);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.z);
            deserializer.Read(out this.reflectivity);
            deserializer.Read(out this.tag);
            deserializer.Read(out this.line);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.offset_time);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.z);
            serializer.Write(this.reflectivity);
            serializer.Write(this.tag);
            serializer.Write(this.line);
        }

        public override string ToString()
        {
            return "CustomPointMsg: " +
            "\noffset_time: " + offset_time.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nz: " + z.ToString() +
            "\nreflectivity: " + reflectivity.ToString() +
            "\ntag: " + tag.ToString() +
            "\nline: " + line.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
