/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

using Newtonsoft.Json;

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Velodyne
{
    public class VelodynePacket : Message
    {
        [JsonIgnore]
        public const string RosMessageName = "velodyne_msgs/VelodynePacket";

        //  Raw Velodyne LIDAR packet.
        public Time stamp;
        //  packet timestamp
        public byte[] data;
        //  packet contents

        public VelodynePacket()
        {
            this.stamp = new Time();
            this.data = new byte[1206];
        }

        public VelodynePacket(Time stamp, byte[] data)
        {
            this.stamp = stamp;
            this.data = data;
        }
    }
}
