//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Nmea
{
    [Serializable]
    public class SentenceMsg : Message
    {
        public const string k_RosMessageName = "nmea_msgs/Sentence";
        public override string RosMessageName => k_RosMessageName;

        //  A message representing a single NMEA0183 sentence.
        //  header.stamp is the ROS Time when the sentence was read.
        //  header.frame_id is the frame of reference reported by the satellite
        //         receiver, usually the location of the antenna.  This is a
        //         Euclidean frame relative to the vehicle, not a reference
        //         ellipsoid.
        public HeaderMsg header;
        //  This should only contain ASCII characters in order to be a valid NMEA0183 sentence.
        public string sentence;

        public SentenceMsg()
        {
            this.header = new HeaderMsg();
            this.sentence = "";
        }

        public SentenceMsg(HeaderMsg header, string sentence)
        {
            this.header = header;
            this.sentence = sentence;
        }

        public static SentenceMsg Deserialize(MessageDeserializer deserializer) => new SentenceMsg(deserializer);

        private SentenceMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.sentence);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.sentence);
        }

        public override string ToString()
        {
            return "SentenceMsg: " +
            "\nheader: " + header.ToString() +
            "\nsentence: " + sentence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
