//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.Std;

namespace RosMessageTypes.Velodyne
{
    [Serializable]
    public class VelodyneScanMsg : Message
    {
        public const string k_RosMessageName = "velodyne_msgs/VelodyneScan";
        public override string RosMessageName => k_RosMessageName;

        //  Velodyne LIDAR scan packets.
        public HeaderMsg header;
        //  standard ROS message header
        public VelodynePacketMsg[] packets;
        //  vector of raw packets

        public VelodyneScanMsg()
        {
            this.header = new HeaderMsg();
            this.packets = new VelodynePacketMsg[0];
        }

        public VelodyneScanMsg(HeaderMsg header, VelodynePacketMsg[] packets)
        {
            this.header = header;
            this.packets = packets;
        }

        public static VelodyneScanMsg Deserialize(MessageDeserializer deserializer) => new VelodyneScanMsg(deserializer);

        private VelodyneScanMsg(MessageDeserializer deserializer)
        {
            this.header = HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.packets, VelodynePacketMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.packets);
            serializer.Write(this.packets);
        }

        public override string ToString()
        {
            return "VelodyneScanMsg: " +
            "\nheader: " + header.ToString() +
            "\npackets: " + System.String.Join(", ", packets.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
